apiVersion: apps/v1
kind: Deployment
metadata:
  name: chore-api
  namespace: fitches
  labels:
    app: chore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chore-api
  template:
    metadata:
      labels:
        app: chore-api
    spec:
      containers:
      - name: rest
        image: docker.io/gaf3/pi-k8s-fitches-nandy-api:0.1-armv7l
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: redis.fitches.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: MYSQL_HOST
            value: mysql.fitches.svc.cluster.local
          - name: MYSQL_PORT
            value: "3306"
          - name: GRAPHITE_HOST
            value: graphite.fitches.svc.cluster.local
          - name: GRAPHITE_PORT
            value: "2003"
        volumeMounts:
        - name: config
          mountPath: /opt/pi-k8s/config
        ports:
        - containerPort: 7865
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /health
            port: 7865
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 7865
      volumes:
        - name: config
          configMap:
            name: chore-api
---
kind: Service
apiVersion: v1
metadata:
  name: chore-api
  namespace: fitches
spec:
  selector:
    app: chore-api
  type: NodePort
  ports:
  - protocol: TCP
    port: 7865
    targetPort: 7865
    nodePort: 30004
